apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: geo-cluster
  region: ap-south-1
  version: "1.28"

iam:
  withOIDC: true

managedNodeGroups:
  - name: general-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true

addons:
  - name: aws-ebs-csi-driver 